name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: war-file
          path: target/*.war

  deploy:
    runs-on: [self-hosted, Linux, X64]
    needs: build
    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: war-file
          path: target

      - name: Stop Tomcat
        run: sudo systemctl stop tomcat

      - name: Deploy to Tomcat9
        run: |
          sudo rm -rf /opt/tomcat/webapps/hello-web /opt/tomcat/webapps/hello-web.war
          sudo cp target/*.war /opt/tomcat/webapps/hello-web.war

      - name: Start Tomcat
        run: sudo systemctl start tomcat
